server:
  port: 8086
  servlet:
    context-path: /application06
logging.level.org.springframework.cache: TRACE

spring:
  redis:
    host: 192.168.1.13
    port: 6379
    password: null
    database: 0


pointcutParam:
  system: order
