server:
  port: 8084
  servlet:
    context-path: /application04
logging.level.org.springframework.cache: TRACE

spring:
  redis:
    host: 192.168.1.13
    port: 6379
    password: null
    database: 0
    timeout: 3000